    sources:
      - path: .
        excludes:
          - project.yml
          - SSHMobile.xcodeproj
          - Design
          - .git
          - .github
          - .gitignore
          - README.md
          - SSHMobile
          - build
          - Payload
